# SPDX-License-Identifier: Apache-2.0
include_guard(GLOBAL)

function(_usdmotion_json_string output value)
    string(REPLACE "\\" "\\\\" value "${value}")
    string(REPLACE "\"" "\\\"" value "${value}")
    string(REPLACE "\n" "\\n" value "${value}")
    string(REPLACE "\r" "\\r" value "${value}")
    string(REPLACE "\t" "\\t" value "${value}")
    set(${output} "\"${value}\"" PARENT_SCOPE)
endfunction()

# Snapshot the actual configured dependency closure, including aliases,
# imported libraries and private static-library dependencies. Raw generator
# expressions are deliberately retained: every alternative must obey policy.
function(usdmotion_write_boundary_graph output)
    set(roots ${ARGN})
    set(pending ${roots})
    set(seen)
    set(nodes_json "")
    set(node_separator "")
    while(pending)
        list(POP_FRONT pending target)
        if(target IN_LIST seen)
            continue()
        endif()
        if(NOT TARGET "${target}")
            message(FATAL_ERROR "Boundary graph target is missing: ${target}")
        endif()
        list(APPEND seen "${target}")
        set(properties ALIASED_TARGET LINK_LIBRARIES INTERFACE_LINK_LIBRARIES
            INTERFACE_LINK_LIBRARIES_DIRECT LINK_OPTIONS INTERFACE_LINK_OPTIONS
            IMPORTED_LOCATION IMPORTED_IMPLIB IMPORTED_LIBNAME
            IMPORTED_LINK_INTERFACE_LIBRARIES IMPORTED_LINK_DEPENDENT_LIBRARIES)
        get_target_property(configurations "${target}" IMPORTED_CONFIGURATIONS)
        foreach(config IN LISTS configurations)
            foreach(property IMPORTED_LOCATION IMPORTED_IMPLIB IMPORTED_LIBNAME
                    IMPORTED_LINK_INTERFACE_LIBRARIES IMPORTED_LINK_DEPENDENT_LIBRARIES)
                list(APPEND properties "${property}_${config}")
            endforeach()
        endforeach()
        set(values_json "")
        set(value_separator "")
        set(edges)
        foreach(property IN LISTS properties)
            get_target_property(value "${target}" "${property}")
            if(NOT value OR value MATCHES "-NOTFOUND$")
                continue()
            endif()
            _usdmotion_json_string(quoted "${value}")
            string(APPEND values_json "${value_separator}${quoted}")
            set(value_separator ",")
            # A target may occur inside $<LINK_ONLY:pkg::target>, nested
            # conditionals or a semicolon list. Try each colon suffix so a
            # generator-expression operator is never part of the target name.
            string(REGEX MATCHALL "[A-Za-z0-9_.:+/-]+" tokens "${value}")
            foreach(token IN LISTS tokens)
                while(NOT token STREQUAL "")
                    if(TARGET "${token}")
                        list(APPEND edges "${token}")
                        break()
                    endif()
                    if(NOT token MATCHES ":")
                        break()
                    endif()
                    string(REGEX REPLACE "^[^:]*:" "" token "${token}")
                endwhile()
            endforeach()
        endforeach()
        list(REMOVE_DUPLICATES edges)
        list(APPEND pending ${edges})
        set(quoted_edges)
        foreach(edge IN LISTS edges)
            _usdmotion_json_string(quoted "${edge}")
            list(APPEND quoted_edges "${quoted}")
        endforeach()
        string(JOIN "," edges_json ${quoted_edges})
        get_target_property(imported "${target}" IMPORTED)
        if(imported)
            set(imported_json true)
        else()
            set(imported_json false)
        endif()
        _usdmotion_json_string(quoted_target "${target}")
        string(APPEND nodes_json "${node_separator}${quoted_target}:{\"imported\":${imported_json},\"properties\":[${values_json}],\"edges\":[${edges_json}]}")
        set(node_separator ",")
    endwhile()
    set(quoted_roots)
    foreach(root IN LISTS roots)
        _usdmotion_json_string(quoted "${root}")
        list(APPEND quoted_roots "${quoted}")
    endforeach()
    string(JOIN "," roots_json ${quoted_roots})
    file(WRITE "${output}" "{\"schema\":1,\"roots\":[${roots_json}],\"targets\":{${nodes_json}}}\n")
endfunction()
